version: '3.7'


services:
  database_queries:
    image: postgres
    container_name: database_queries
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app: 
    build: .
    container_name: appchallenge
    ports:
      - "3333:3333"
    volumes:
      - ".:/usr/app"
    network_mode: host
volumes:
  pgdata:
    driver: local      